# **TUGAS 4**

Proyek Missing Values Inputation + Materi Normalisasi data
1. Missing values : menyelesaikan dengan WKNN (manual)  + code menghitung WKNN
2. Normalisasi data (materi)
    - macam macam normalisasi data dan beri contoh hasil normalisasi data
    - Gunakan library sklearn untuk melakukan normalisasi data atau membuat fungsi sendiri

Perhitungan :
- Preprocessing (macam-macam normalisasi data)
- normalisasi merupakan tahapan preprocessing
- pengerjaan missing value dengan WKNN

------------------------------------------------

1. PENGERTIAN MISSING VALUE

Missing value adalah kondisi dimana suatu atribut dalam dataset tidak memiliki nilai atau bernilai kosong. Hal ini sering terjadi karena kesalahan input, data tidak lengkap, atau kegagalan sistem saat pengumpulan data.

Dampak:

Mengurangi kualitas data

Menurunkan akurasi model

Menghambat proses analisis

Missing value dapat menyebabkan proses klasifikasi menjadi tidak optimal karena data tidak lengkap

2. IMPUTASI MISSING VALUE

Imputasi adalah proses mengisi nilai yang hilang dengan nilai pengganti berdasarkan metode tertentu.

Tujuan:
- Menghindari penghapusan data
- Menjaga jumlah dataset tetap utuh
- Meningkatkan performa model

Metode umum:
- Mean / rata-rata
- Median
- Modus
- KNN Imputation
- WKNN (Weighted KNN)

Penggunaan metode imputasi terbukti dapat meningkatkan akurasi dibandingkan membiarkan data kosong

3. KNN UNTUK MISSING VALUE

Metode K-Nearest Neighbor (KNN) digunakan untuk mengisi nilai kosong dengan melihat data terdekat (tetangga) berdasarkan kemiripan.

Konsep:
- Hitung jarak antar data
- Ambil K data terdekat
- Gunakan nilai mereka sebagai acuan

KNN menggunakan jarak (biasanya Euclidean) untuk menentukan kemiripan antar data.

4. WEIGHTED KNN (WKNN)

WKNN adalah pengembangan dari KNN, dimana setiap tetangga memiliki bobot berdasarkan jaraknya.

Konsep utama:
- Data yang lebih dekat → pengaruh lebih besar
- Data yang jauh → pengaruh lebih kecil

Rumus bobot:

$$
w_i = \frac{1}{d_i}
$$

Rumus prediksi:​

$$
\hat{y} = \frac{\sum_{i=1}^{k} w_i \cdot y_i}{\sum_{i=1}^{k} w_i}
$$


WKNN lebih akurat dibanding KNN biasa karena mempertimbangkan tingkat kedekatan data

5. LANGKAH-LANGKAH WKNN

- Melakukan preprocessing (normalisasi data)
- Menentukan data yang memiliki missing value
- Menghitung jarak ke semua data lain
- Mengurutkan jarak (terkecil ke terbesar)
- Mengambil K tetangga terdekat
- Menghitung bobot tiap tetangga
- Menghitung nilai imputasi menggunakan rumus WKNN
- Mengisi nilai missing dengan hasil tersebut


6. KELEBIHAN DAN KEKURANGAN WKNN

**Kelebihan:**

- Lebih akurat dari KNN biasa
- Mempertimbangkan kedekatan data
- Cocok untuk imputasi missing value

**Kekurangan:**

- Perhitungan lebih kompleks
- Sensitif terhadap nilai K
- Membutuhkan preprocessing (normalisasi)

## 1. PREPROCESSING DATA

Preprocessing = tahap awal sebelum pemodelan

Tujuan:

- Mengatasi data tidak lengkap (missing value)
- Menyamakan skala data (normalisasi)

## 2. NORMALISASI DATA

###A. Pengertian

Normalisasi : proses mengubah skala data agar berada dalam rentang tertentu (biasanya 0–1)

Normalisasi dilakukan agar semua fitur memiliki skala yang sama, sehingga tidak ada fitur yang mendominasi perhitungan jarak.

Tanpa normalisasi:
- Data besar (contoh: 3.000.000) akan mendominasi
- Hasil jarak menjadi tidak akurat

Dengan normalisasi:
- Semua fitur berada dalam rentang yang sama
- Perhitungan KNN/WKNN lebih adil


### B. Macam-macam Normalisasi
####1. Min-Max Normalization

Rumus:

$$
X' = \frac{X - X_{min}}{X_{max} - X_{min}}
$$

Contoh (IPK):
- Min = 2
- Max = 4

| IPK | Hasil |
| --- | ----- |
| 2   | 0     |
| 3   | 0.5   |
| 4   | 1     |

####2. Z-Score Normalization

Rumus:

$$
X' = \frac{X - \mu}{\sigma}
$$

$$
\mu = \text{mean}, \quad \sigma = \text{standar deviasi}
$$

Contoh:
- Mean IPK = 2.86
- Std = 0.83

| IPK | Hasil (≈) |
| --- | --------- |
| 2   | -1.03     |
| 3   | 0.17      |
| 4   | 1.37      |

####3. Decimal Scaling

Rumus:

$$
X' = \frac{X}{10^j}
$$

Contoh PO:
| PO      | Hasil |
| ------- | ----- |
| 2000000 | 0.2   |
| 3000000 | 0.3   |
| 4000000 | 0.4   |

### C. Implementasi dengan sklearn

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# =========================
# 1. DATA AWAL
# =========================
df = pd.DataFrame({
    'IPK': [2,3,4,2,3,4,2],
    'PO': [2000000,3000000,2000000,2000000,3000000,4000000,3000000],
    'JML': [2,3,2,3,2,3,np.nan]
})

df

   IPK       PO   JML
0    2  2000000 2.000
1    3  3000000 3.000
2    4  2000000 2.000
3    2  2000000 3.000
4    3  3000000 2.000
5    4  4000000 3.000
6    2  3000000   NaN

## 3. MISSING VALUE (WKNN)
### A. Data yang Hilang

Baris ke-7:

IPK = 2

PO = 3000000

JML = ❓

## B. Data Normalisasi (dipakai hitung jarak)

In [ ]:
# =========================
# 2. NORMALISASI
# =========================
scaler = MinMaxScaler()

df_norm = df.copy()
df_norm[['IPK','PO']] = scaler.fit_transform(df[['IPK','PO']])

df_norm

    IPK    PO   JML
0 0.000 0.000 2.000
1 0.500 0.500 3.000
2 1.000 0.000 2.000
3 0.000 0.000 3.000
4 0.500 0.500 2.000
5 1.000 1.000 3.000
6 0.000 0.500   NaN

### C. Hitung Jarak (Euclidean)

Rumus:

$$
d = \sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2}
$$
atau
$$
d = \sqrt{\sum_{i=1}^{n} (x_i - y_i)^2}
$$

Contoh ke data 1:

$$
d = \sqrt{(0 - 0)^2 + (0.5 - 0)^2}
$$

In [ ]:
# =========================
# 3. HITUNG JARAK
# =========================
train = df_norm.dropna()
test = df_norm[df_norm['JML'].isna()]

X_train = train[['IPK','PO']].values
y_train = train['JML'].values
X_test = test[['IPK','PO']].values[0]

# hitung jarak
distances = np.sqrt(np.sum((X_train - X_test)**2, axis=1))

df_jarak = train.copy()
df_jarak['Jarak'] = distances

df_jarak

    IPK    PO   JML  Jarak
0 0.000 0.000 2.000  0.500
1 0.500 0.500 3.000  0.500
2 1.000 0.000 2.000  1.118
3 0.000 0.000 3.000  0.500
4 0.500 0.500 2.000  0.500
5 1.000 1.000 3.000  1.118

### D. Ambil K Terdekat (misal K=3)

Ambil jarak terkecil:

Data terdekat:

No 1 → JML = 0

No 2 → JML = 1

No 4 → JML = 1

In [ ]:
# =========================
# 4. K TETANGGA TERDEKAT
# =========================
k = 3
df_k = df_jarak.nsmallest(k, 'Jarak')

df_k

    IPK    PO   JML  Jarak
0 0.000 0.000 2.000  0.500
1 0.500 0.500 3.000  0.500
3 0.000 0.000 3.000  0.500

### E. Hitung WKNN (Weighted KNN)

Rumus bobot:

$$
w_i = \frac{1}{d_i}
$$

Hitung hasil:

$$
\hat{y} = \frac{\sum_{i=1}^{k} w_i \cdot y_i}{\sum_{i=1}^{k} w_i}
$$

In [ ]:
# =========================
# 5. BOBOT WKNN
# =========================
df_k['Bobot'] = 1 / df_k['Jarak']

df_k

    IPK    PO   JML  Jarak  Bobot
0 0.000 0.000 2.000  0.500  2.000
1 0.500 0.500 3.000  0.500  2.000
3 0.000 0.000 3.000  0.500  2.000

### F. Hasil Akhir

JML ≈ 1 (dibulatkan)

In [ ]:
# =========================
# 6. HASIL AKHIR
# =========================
hasil = np.sum(df_k['Bobot'] * df_k['JML']) / np.sum(df_k['Bobot'])

hasil, round(hasil)

(np.float64(2.6666666666666665), 3)

## 4. HASIL AKHIR

In [ ]:
# =========================
# 7. DATA AKHIR
# =========================
df_final = df.copy()
df_final.loc[df_final['JML'].isna(), 'JML'] = round(hasil)

df_final

   IPK       PO   JML
0    2  2000000 2.000
1    3  3000000 3.000
2    4  2000000 2.000
3    2  2000000 3.000
4    3  3000000 2.000
5    4  4000000 3.000
6    2  3000000 3.000



1. Berdasarkan hasil perhitungan jarak terhadap data terdekat:
    - Dipilih K = 3 tetangga terdekat
    - Nilai tetangga yang digunakan adalah: 0, 1, dan 1

2. Setelah dilakukan pembobotan (WKNN):
    - Diperoleh nilai hasil imputasi sebesar 0.67

3. Karena nilai target (JML) bersifat diskrit (kategori/bilangan bulat), maka:
    - Hasil dibulatkan menjadi 1


**Nilai missing pada data baris ke-7 untuk variabel JML adalah = 1**